name: Local Env CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  local-env:
    name: Setup Dev Container and Run Commands
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup and Start Dev Container
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          kind create cluster --name to-dos --config kind-local-config.yaml --kubeconfig ./.to-dos-cluster-kubeconfig
          helmfile cache cleanup && helmfile --environment local --namespace local -f deploy/helmfile.yaml apply

  to-dos-ui:
    name: Run Commands from to-dos-ui
    runs-on: ubuntu-latest
    needs: local-env
    steps:
    - name: Checkout UI repository
      uses: actions/checkout@v4
      with:
        repository: FaceMan01/to-dos-ui
        path: to-dos-ui

    - name: Setup and Start Dev Container
      uses: devcontainers/ci@v0.3
      with:
        configFile: ./to-dos-ui/.devcontainer/devcontainer.json
        runCmd: |
          cd to-dos-ui
          npm ci
          npm audit fix
          npm run test
          npm run cypress:run:e2e:local-env

