name: Local Env CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  e2e-test:
    name: Setup Local Environment
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup and Start Dev Container
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          kind create cluster --name to-dos --config kind-local-config.yaml --kubeconfig ./.to-dos-cluster-kubeconfig
          helmfile cache cleanup && helmfile --environment local --namespace local -f deploy/helmfile.yaml apply

    - name: Checkout UI repository
      uses: actions/checkout@v4
      with:
        repository: FaceMan01/to-dos-ui
        path: to-dos-ui

    - name: Build UI Docker image
      run: |
        cd to-dos-ui
        docker build -t to-dos-ui:latest .

    - name: Run UI Docker Container
      run: |
        docker run -d --name to-dos-ui to-dos-ui

    - name: Run Tests
      run: |
        docker exec to-dos-ui npm ci
        docker exec to-dos-ui npm audit fix
        docker exec to-dos-ui npm run start-local-env &
        sleep 10
        docker exec to-dos-ui npm run test
        docker exec to-dos-ui npm run cypress:run:e2e:local-env
