name: Local Env CI

on:
  pull_request:
    branches:
      - master

jobs:
  local-env:
    name: Setup Local Environment
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Local Env repository
      uses: actions/checkout@v4

    - name: Setup and Start Local Env Dev Container
      uses: devcontainers/ci@v0.3
      with:
        runCmd: |
          kind create cluster --name to-dos --config kind-local-config.yaml --kubeconfig ./.to-dos-cluster-kubeconfig
          helmfile cache cleanup && helmfile --environment local --namespace local -f deploy/helmfile.yaml apply

    - name: Checkout UI repository
      uses: actions/checkout@v4
      with:
        repository: FaceMan01/to-dos-ui
        ref: hotfix-local-env-test
        path: to-dos-ui

    - name: Setup and Start UI Dev Container
      uses: devcontainers/ci@v0.3
      with:
        configFile: ./to-dos-ui/.devcontainer/devcontainer.json
        runCmd: |
          echo "127.0.0.1       to-dos.local.tourmalinecore.internal" >> /etc/hosts
          curl http://to-dos.local.tourmalinecore.internal:40080/
          cd to-dos-ui
          npm ci
          npm run cypress:run:e2e:local-env

